In [4]:
#LSTM
import numpy as np

In [6]:
def sigmoid(x): #sigmoid function
    return 1/(1+np.exp(-x))

def tanh(x): #tanh function tangens hiperblocziny
    return np.tanh(x)

In [7]:
input_s=5 #input size
hidden_s=5 #hidden layer size

In [9]:
#wagi dla komórek poniważ są 4 bramki
Wf= np.random.random((hidden_s,hidden_s+input_s)) #wagi dla forget gate wielkość wyjścia ma być jak hidden size a drugi parametr to polaczone info
Wis= np.random.random((hidden_s,hidden_s+input_s)) #wagi dla input s gate
Wit= np.random.random((hidden_s,hidden_s+input_s)) #wagi dla input t gate
Wo= np.random.random((hidden_s,hidden_s+input_s))#wagi dla output gate

#biasy
bf= np.random.random(hidden_s) #bias dla forget gate
bis= np.random.random(hidden_s) #bias dla input s gate
bit= np.random.random(hidden_s) #bias dla input t gate
bo= np.random.random(hidden_s) #bias dla output gate




In [10]:
stan_h= np.zeros((1,hidden_s)) #stan ukryty
stan_c= np.zeros((1,hidden_s)) #stan komórki


In [13]:
#funkcja która wykona wszystko

def LSTM(sh,sc,x, Wf, Wis, Wit, Wo, bf, bis, bit, bo):
    #sh- stan ukryty
    #sc- stan komórki
    #x- wejście
    #Wf- wagi forget gate
    #Wis- wagi input s gate
    #Wit- wagi input t gate
    #Wo- wagi output gate
    #bf- bias forget gate
    #bis- bias input s gate
    #bit- bias input t gate
    #bo- bias output gate
        
    #połączenie sygnałów
    sygnal = np.hstack((sh,x.reshape(1,-1))).T #połączenie stanu ukrytego i wejścia i transpozycja
    #mnożenie
    forgot= sigmoid(np.matmul(Wf,sygnal)+bf) #forget gate
    
    czy_dodac= sigmoid(np.matmul(Wis,sygnal)+bis) #czy dodać 
    ile_dodac= tanh(np.matmul(Wit,sygnal)+bit) #ile dodać do stanu komórki
    
    wyjscie=sigmoid(np.matmul(Wo,sygnal)+bo) #output gate 
    
    #obliczeni stanu komórki stac
    stan_c=sc*forgot + czy_dodac*ile_dodac
    
    #obliczenie stanu ukrytego
    stan_h= wyjscie*tanh(stan_c)
    return stan_c, stan_h #LSTM zwraca wyjściową wartość neuronu również jako pierwszy argument więc na przykład można podłączyć dense pod to

In [15]:
#test
#potrzebujemy jakieś dane jedne ciąg danych
X = np.random.random(input_s)
X



array([0.56371095, 0.98800784, 0.24818815, 0.34363388, 0.20235982])

In [16]:
#uruchomienie
stan_h, stan_c=  LSTM(stan_h,stan_c,X,Wf,Wis,Wit,Wo,bf,bis,bit,bo)

In [17]:
stan_h

array([[0.8031219 , 0.80037781, 0.87906013, 0.87783282, 0.88353492],
       [0.67437165, 0.6745469 , 0.78942643, 0.77588426, 0.80109869],
       [0.78790409, 0.78675153, 0.86951836, 0.86376851, 0.87601074],
       [0.73793805, 0.73648349, 0.835181  , 0.82826109, 0.84310025],
       [0.70667396, 0.7000365 , 0.81172229, 0.81711895, 0.81557777]])

In [18]:
stan_c

array([[0.6298352 , 0.5957306 , 0.62315833, 0.64079839, 0.65579689],
       [0.50991418, 0.44950334, 0.48538073, 0.51219248, 0.54751129],
       [0.58919913, 0.53263633, 0.55260885, 0.58002577, 0.60641442],
       [0.58040216, 0.53824608, 0.5739133 , 0.59379159, 0.61679266],
       [0.53749851, 0.47719405, 0.51268393, 0.54605186, 0.56757478]])

In [21]:
#możemy oczywiście użyć kerasa aby ułątwić sobie życie i nie pisać samodzielnie LSTM oraz metody uczenia wstecznej proagacji przez czas
from tensorflow.keras.layers import LSTM